[package]
name = "mandelbrot_sextant"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
bit-vec = "0.8.0"
rayon = "1.10.0"

[dev-dependencies]
paste = "1.0.15"

[profile.dev]
opt-level=3
